# Generated by Django 5.1.2 on 2024-12-25 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuerNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.issuer')),
            ],
            options={
                'verbose_name_plural': 'Issuer News',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['published_date'], name='core_issuer_publish_4c4841_idx'), models.Index(fields=['issuer', 'published_date'], name='core_issuer_issuer__3347b8_idx')],
            },
        ),
    ]